In [4]:
import numpy as np
# Creating an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Calculating mean
mean = np.mean(array)
print("Mean:", mean)
# Calculating median
median = np.median(array)
print("Median:", median)
# Calculating standard deviation
std_dev = np.std(array)
print("Standard Deviation:", std_dev)
# Finding minimum and maximum values
min_val = np.min(array)
max_val = np.max(array)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x3x2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
